### PR TITLE
Update autos 

### PR DESCRIPTION
**Pull request by alicekuznetsov**
need to mirror for open still

### CODE REVIEW

**Comment by TaylerUva** [comment]
CoCuHighDock is not attempting to dock in either cable or open. @ACat701 do you see any reasons this may not be working?

**Comment by alicekuznetsov** [comment]
Assuming your code is the same as whats commited, I dont see any code issues. Are the paths correct? If you're seeing rainbow LEDs, its running the command @TaylerUva

**Comment by TaylerUva** [comment]
> Assuming your code is the same as whats commited, I dont see any code issues. Are the paths correct? If you're seeing rainbow LEDs, its running the command @TaylerUva 

It looks like it's not continuing the path after placing. Cable version was untouched and also does not attempt dock @ACat701

**Comment by alicekuznetsov** [comment]
> > Assuming your code is the same as whats commited, I dont see any code issues. Are the paths correct? If you're seeing rainbow LEDs, its running the command @TaylerUva 
> 
> It looks like it's not continuing the path after placing. Cable version was untouched and also does not attempt dock @ACat701 

I would check out pathplanner. Delete unused paths and make sure all of the names match in Drivetrain. I don't think its a code issue if Cable isnt working now

**Comment by alicekuznetsov** [comment]
I think we are ready for the seal of approval @FRCTeam3255/code-reviewers 

68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f31337a65453971514e4335494b6b2f67697068792e676966

> Unless we think the pose estimator not receiving the yaw is a code issue... which I find unlikely. I don't think we made any significant changes to the code that would cause something like that before we saw the issue. Maybe something is shorting to the frame? Idk. If this gets merged in I can pull on my advantagescope branch and just start logging random nonsense

**Review by TaylerUva — APPROVED** [review]

**Pull request merged**
